// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yahcbigzuknluctdoaba.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlhaGNiaWd6dWtubHVjdGRvYWJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1MjQ1NTUsImV4cCI6MjA2NjEwMDU1NX0.vmHLbS-oaN0AJtk6d5Ow__pjj76bC0P_BU9FpqnDyIA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);